name: backend-express
description: Stack typescript with express for backend
types:
  - app-template
inputs:
  - label: "Project name(must not have spaces and be lowercase)"
    type: text
    name: "application_name"
    default: "backend_express"
